# Generated by Django 4.0.5 on 2022-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_questions_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
